[book]
title = "Laundry Data"
authors = ["Buckydev"]
language = "en"
src = "docs/"

[build]
extra-watch-dirs = ["out/"]

[output.html]
site-url = "/laundry-data/"
git-repository-url = "https://github.com/Stinky-c/laundry-data/"