[env]
DB_TYPE = "sqlite"
DB_HOST = ""
DB_PORT = ""
DB_NAME = ""
DB_USER = ""
DB_PASS = ""
DB_PATH = "./testing.db"

[vars]
feature = "sqlite"

[tasks]
[tasks."app:run"]
extends = "app:run"

[tasks."app:build"]
extends = "app:build"

[tasks."app:clean"]
extends = "app:clean"

[tasks."db:clean"]
extends = "db:clean"
run = "rm -r testing.db*"
