[env]
DB_TYPE = "sqlite"
DB_HOST = ""
DB_PORT = ""
DB_NAME = ""
DB_USER = ""
DB_PASS = ""
DB_PATH = "./sqlitedata/sqlite.db"

[vars]
feature = "sqlite"
data_dir = "sqlitedata"

[tasks]
[tasks."app:run"]
extends = "app:run"

[tasks."app:build"]
extends = "app:build"

[tasks."app:check"]
extends = "app:check"

[tasks."app:deps"]
extends = "app:deps"

[tasks."db:clean"]
extends = "db:clean"
run = "rm -r {{vars.data_dir}}"
run_windows = "rmdir {{vars.data_dir}}"

[tasks."db:pre"]
extends = "db:pre"
